const moduleVersion = new URL(import.meta.url).searchParams.get("v") || "dev";
const { database } = await import(`../data/database.js?v=${encodeURIComponent(moduleVersion)}`);

const TURBO_WEEK_STATE_PREFIX = "harvesthub_turbo_vs_week_state:";
const TROOP_LEVEL_DEFAULTS = [8, 9, 10];
let isSyncingControls = false;
let currentDayId = "";
let selectedManually = false;
let timerId = null;

function getWeekStateKey(){return `${TURBO_WEEK_STATE_PREFIX}local`}
function readWeekState(){try{return JSON.parse(localStorage.getItem(getWeekStateKey())||"{}")}catch{return {}}}
function writeWeekState(state){localStorage.setItem(getWeekStateKey(),JSON.stringify(state))}
function formatNumber(value){return Math.round(Number(value)||0).toLocaleString("ru-RU")}
function getActionById(actionId){return database.action.find(action=>action.id===actionId)}
function resolveDayList(list=[]){return list.flatMap(item=>{if(typeof item==="string")return item;if(item.type==="action")return item.id;if(item.type==="category")return database.action.filter(action=>action.categoryId===item.id).map(action=>action.id);if(item.type==="text")return item;return []})}
function sortDayItems(items){return [...items].sort((a,b)=>{if(typeof a!=="string"&&typeof b!=="string")return 0;if(typeof a!=="string")return 1;if(typeof b!=="string")return -1;const aa=getActionById(a);const bb=getActionById(b);if(!aa||!bb)return 0;const ca=database.category.findIndex(category=>category.id===aa.categoryId);const cb=database.category.findIndex(category=>category.id===bb.categoryId);if(ca!==cb)return ca-cb;return database.action.findIndex(action=>action.id===a)-database.action.findIndex(action=>action.id===b)})}
function getCurrentUtcDayId(){const utcDayId=typeof window.getHarvestHubUtcDayId==="function"?window.getHarvestHubUtcDayId():null;return utcDayId&&database.days[utcDayId]?utcDayId:database.dayOrder[0]}
function getPoints(actionId,eventType,level=null){const points=getActionById(actionId)?.points?.[eventType];if(points==null)return 0;if(typeof points==="object")return Number(points[level])||0;return Number(points)||0}
function getQuantityControl(row){return row.querySelector("input[data-action-id], select[data-action-id]")}
function getRowActionId(row){return row.dataset.actionId||getQuantityControl(row)?.dataset.actionId||row.querySelector(".action-level-select")?.dataset.levelActionId||""}
function getRowEventType(row){return row.dataset.eventType||row.querySelector("[data-event-type]")?.dataset.eventType||""}
function getTroopRowsFromState(state={}){const sourceRows=Array.isArray(state.rows)?state.rows:Array.isArray(state.stages)?state.stages.map(stage=>({level:stage.level,value:stage.troops??stage.value})):[];if(sourceRows.length>0)return sourceRows.slice(0,3).map((row,index)=>({level:String(row.level??TROOP_LEVEL_DEFAULTS[index]??10),value:String(row.value??row.troops??"0")}));if(state.value!=null||state.level!=null)return[{level:String(state.level??10),value:String(state.value??"0")}];return[]}
function getRowState(row){if(row.classList.contains("action-row-multi-level")){const rows=Array.from(row.querySelectorAll(".action-multi-line")).map(line=>({level:line.querySelector("select")?.value||"",value:line.querySelector("input")?.value||"0"}));const filled=rows.filter(item=>Number(item.value)>0);const last=filled[filled.length-1]||rows[rows.length-1]||{level:"",value:"0"};return{value:String(Math.max(0,...rows.map(item=>Number(item.value)||0))),level:last.level||null,rows}}const quantityControl=getQuantityControl(row);const levelSelect=row.querySelector(".action-level-select");return{value:quantityControl?.value||"0",level:levelSelect?.value||null}}
function setRowState(row,state={}){if(row.classList.contains("action-row-multi-level")){const savedRows=getTroopRowsFromState(state);Array.from(row.querySelectorAll(".action-multi-line")).forEach((line,index)=>{const levelSelect=line.querySelector("select");const quantityInput=line.querySelector("input");const saved=savedRows[index];if(levelSelect)levelSelect.value=String(saved?.level??TROOP_LEVEL_DEFAULTS[index]??10);if(quantityInput)quantityInput.value=String(saved?.value??"0")});return}const quantityControl=getQuantityControl(row);const levelSelect=row.querySelector(".action-level-select");if(quantityControl)quantityControl.value=String(state?.value??"0");if(levelSelect&&state?.level!=null)levelSelect.value=String(state.level)}
function saveCurrentDayState(){if(!currentDayId)return;const state=readWeekState();state[currentDayId]={turtle:{},vs:{}};document.querySelectorAll(".action-row").forEach(row=>{const actionId=getRowActionId(row);const eventType=getRowEventType(row);if(!actionId||!eventType)return;state[currentDayId][eventType][actionId]=getRowState(row)});writeWeekState(state)}
function restoreDayState(dayId){const dayState=readWeekState()[dayId];if(!dayState)return;document.querySelectorAll(".action-row").forEach(row=>{const actionId=getRowActionId(row);const eventType=getRowEventType(row);if(!actionId||!eventType)return;setRowState(row,dayState[eventType]?.[actionId])})}
function createTextRow(text){const row=document.createElement("div");row.className="action-row action-row-text";row.textContent=text;return row}
function createQuantitySelect(action,eventType){const select=document.createElement("select");select.className="action-quantity-select";select.dataset.actionId=action.id;select.dataset.eventType=eventType;select.dataset.noPersist="true";const zero=document.createElement("option");zero.value="0";zero.textContent="0";select.appendChild(zero);for(let value=action.quantityOptions.min;value<=action.quantityOptions.max;value++){const option=document.createElement("option");option.value=value;option.textContent=value;select.appendChild(option)}return select}
function createNumberInput(action,eventType){const input=document.createElement("input");input.type="number";input.min="0";input.value="0";input.dataset.actionId=action.id;input.dataset.eventType=eventType;input.dataset.noPersist="true";return input}
function createLevelSelect(action,eventType,defaultLevel){const select=document.createElement("select");select.className="action-level-select";select.dataset.levelActionId=action.id;select.dataset.eventType=eventType;select.dataset.noPersist="true";action.options.forEach(optionData=>{const option=document.createElement("option");option.value=optionData.value;option.textContent=optionData.label;select.appendChild(option)});select.value=String(defaultLevel);return select}
function createTroopMultiControls(action,eventType){const controls=document.createElement("div");controls.className="action-controls action-multi-controls";TROOP_LEVEL_DEFAULTS.forEach(defaultLevel=>{const line=document.createElement("div");line.className="action-multi-line";const levelSelect=createLevelSelect(action,eventType,defaultLevel);const quantityInput=createNumberInput(action,eventType);quantityInput.className="action-quantity-input";quantityInput.dataset.hasLevel="true";line.append(levelSelect,quantityInput);controls.appendChild(line)});return controls}
function createActionRow(action,eventType){const row=document.createElement("div");row.className="action-row";row.dataset.actionId=action.id;row.dataset.eventType=eventType;const label=document.createElement("label");label.textContent=action.name;let controls;if(action.id==="troop_upgrade"&&action.options){row.classList.add("action-row-multi-level");controls=createTroopMultiControls(action,eventType)}else{controls=document.createElement("div");controls.className="action-controls";if(action.options){row.classList.add("action-row-with-level");const levelSelect=createLevelSelect(action,eventType,action.options[0]?.value??1);const quantityInput=createNumberInput(action,eventType);quantityInput.className="action-quantity-input";quantityInput.dataset.hasLevel="true";controls.append(levelSelect,quantityInput)}else{controls.appendChild(action.quantityOptions?createQuantitySelect(action,eventType):createNumberInput(action,eventType))}}row.append(label,controls);row.querySelectorAll("input, select").forEach(control=>{control.addEventListener(control.tagName==="SELECT"?"change":"input",()=>handleControlChange(action.id,control))});return row}
function syncActionControls(actionId,sourceControl){if(isSyncingControls)return;isSyncingControls=true;const sourceRow=sourceControl.closest(".action-row");const sourceState=getRowState(sourceRow);document.querySelectorAll(".action-row").forEach(row=>{if(row===sourceRow)return;if(getRowActionId(row)!==actionId)return;setRowState(row,sourceState)});isSyncingControls=false}
function calculateRowTotal(row){const eventType=getRowEventType(row);const actionId=getRowActionId(row);if(row.classList.contains("action-row-multi-level")){return Array.from(row.querySelectorAll(".action-multi-line")).reduce((sum,line)=>sum+(Number(line.querySelector("input")?.value)||0)*getPoints(actionId,eventType,line.querySelector("select")?.value||null),0)}const quantityControl=getQuantityControl(row);return (Number(quantityControl?.value)||0)*getPoints(actionId,eventType,row.querySelector(".action-level-select")?.value||null)}
function updateTotals(){let turtleTotal=0;let vsTotal=0;document.querySelectorAll(".action-row").forEach(row=>{const total=calculateRowTotal(row);const eventType=getRowEventType(row);if(eventType==="turtle")turtleTotal+=total;if(eventType==="vs")vsTotal+=total});if(document.getElementById("turtleTotal"))document.getElementById("turtleTotal").textContent=formatNumber(turtleTotal);if(document.getElementById("vsTotal"))document.getElementById("vsTotal").textContent=formatNumber(vsTotal)}
function handleControlChange(actionId,sourceControl){syncActionControls(actionId,sourceControl);updateTotals();saveCurrentDayState()}
function renderEventList(container,list,eventType){container.innerHTML="";sortDayItems(resolveDayList(list)).forEach(item=>{if(typeof item!=="string"){container.appendChild(createTextRow(item.text));return}const action=getActionById(item);if(action)container.appendChild(createActionRow(action,eventType))})}
function renderDay(dayId){const day=database.days[dayId];const turtleList=document.getElementById("turtleList");const vsList=document.getElementById("vsList");if(!day||!turtleList||!vsList)return;saveCurrentDayState();currentDayId=dayId;renderEventList(turtleList,day.turtle,"turtle");renderEventList(vsList,day.vs,"vs");restoreDayState(dayId);updateTotals()}
function fillDaySelector(){const selector=document.getElementById("daySelector");if(!selector)return;selector.innerHTML="";database.dayOrder.forEach(dayId=>{const option=document.createElement("option");option.value=dayId;option.textContent=database.days[dayId].name;selector.appendChild(option)});selector.addEventListener("change",()=>{selectedManually=true;renderDay(selector.value)})}
function selectCurrentUtcDay(){const selector=document.getElementById("daySelector");if(!selector)return;const dayId=getCurrentUtcDayId();selector.value=dayId;renderDay(dayId)}
export function init(){fillDaySelector();selectCurrentUtcDay();window.addEventListener("harvesthub:utc-day-change",()=>{if(selectedManually)return;selectCurrentUtcDay()});if(timerId)clearInterval(timerId);timerId=setInterval(()=>{if(!selectedManually)selectCurrentUtcDay()},60000)}
